DjangoPolls/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from polls.api_views import QuestionViewSet, AnswerViewSet, VoteViewSet

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()

router.register(r'answers', AnswerViewSet)
router.register(r'questions', QuestionViewSet)
router.register(r'votes', VoteViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls', namespace="polls")),
    path('api-auth/', include('rest_framework.urls')),
    path('api/v0/', include(router.urls)),
]

polls/urls.py
from django.urls import path
from polls import views
from django.contrib.auth.views import LogoutView

app_name = 'polls'

urlpatterns = [
    path('', views.main_view, name='index'),
    path('questions/', views.QuestionsListView.as_view(), name='questions'),
    path('<int:question_id>/', views.question_detail_view, name='question'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('<int:question_id>/result/', views.result, name='result'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.UserCreateView.as_view(), name='register'),
    path('newpoll/', views.new_poll, name='newpoll'),
    path('update/', views.update, name='update'),

]

polls/models.py
from django.db import models
from datetime import date
from django.contrib.auth.models import User


# Create your models here.
class Answer(models.Model):
    answer = models.CharField(max_length=64)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.answer


class Question(models.Model):
    title = models.CharField(max_length=128, verbose_name="Question", default='Where to have a lunch?')
    date_published = models.DateField(default=date.today)
    answers = models.ManyToManyField(Answer)
    result = models.CharField(max_length=64,
                              blank=True,
                              null=True,
                              verbose_name="Result")

    def __str__(self):
        return self.title


class Info(models.Model):
    text = models.CharField(max_length=64, unique=False)

    def __str__(self):
        return self.text


class Description(models.Model):
    date_published = models.DateField(default=date.today)
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
    text_info = models.ForeignKey(Info, on_delete=models.CASCADE)
    digital_info = models.DecimalField(decimal_places=2, default=0, max_digits=5)


class VotesCounter(models.Model):
    answer = models.ForeignKey(Answer,
                               on_delete=models.CASCADE,
                               verbose_name="Answer")
    question = models.ForeignKey(Question,
                                 on_delete=models.CASCADE,
                                 verbose_name="Question",
                                 related_name='question_votes_counters'
                                 )
    votes = models.IntegerField(verbose_name="Votes", default=0)

    def __str__(self):
        return self.answer.answer


class Voter(models.Model):
    date = models.DateField(default=date.today)
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="User")
    question = models.ForeignKey(Question,
                                 on_delete=models.CASCADE,
                                 verbose_name='Question')

    answer = models.ForeignKey(VotesCounter, on_delete=models.CASCADE, verbose_name='Answer')

    def __str__(self):
        return self.user.username

    def voted_already(self):
        user_list = Voter.objects.filter(user=self.user, question=self.question)
        return len(user_list) > 0

polls/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User
from .models import Question, Answer


class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')


class QuestionForm(forms.ModelForm):
    title = forms.CharField(label='Question',
                            widget=forms.TextInput(attrs={'placeholder': 'Question', 'class': 'form-control'}))

    answers = forms.ModelMultipleChoiceField(label='Options',
                                             queryset=Answer.objects.filter(is_active=True),
                                             widget=forms.CheckboxSelectMultiple())

    class Meta:
        model = Question
        fields = ('title', 'answers')

polls/views.py
import random

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, CreateView
from django.contrib.auth.views import LoginView
from django.contrib.auth.models import User
from datetime import date, datetime
from random import randrange
from .models import Question, Voter, VotesCounter, Answer, Description, Info
from .forms import RegistrationForm, QuestionForm


# Create your views here.
def main_view(request):
    return render(request, 'polls/index.html')


class UserLoginView(LoginView):
    template_name = 'polls/login.html'


class UserCreateView(CreateView):
    model = User
    template_name = 'polls/register.html'
    form_class = RegistrationForm
    success_url = reverse_lazy('polls:login')


class QuestionsListView(LoginRequiredMixin, ListView):
    template_name = 'polls/questions.html'
    context_object_name = 'we_have_questions'

    def get_queryset(self):
        """Return filtered questions"""
        if datetime.now().hour < 23:
            questions = Question.objects \
                .filter(date_published=date.today()) \
                .order_by('-date_published')
            return questions


@login_required
def question_detail_view(request, question_id):
    question = get_object_or_404(Question, id=question_id)

    voter = Voter()
    voter.user = request.user
    voter.question = question
    if voter.voted_already():
        return render(request, 'polls/question.html', {
            'question': question,
            'error_message': "You already voted",

        })
    else:
        return render(request, 'polls/question.html', {
            'question': question,

        })


@login_required
def vote(request, question_id):
    question = get_object_or_404(Question, id=question_id)

    if request.POST.get('answer'):
        try:
            selected_answer = question.question_votes_counters.get(id=request.POST['answer'])
        except (question.question_votes_counters.get(id=request.POST['answer']).DoesNotExist,
                UnicodeEncodeError,
                ValueError):
            return render(request, 'polls/question.html', {
                'question': question,
                'error_message': "Invalid answer",
            })

        selected_answer.votes += 1
        selected_answer.save()

        voter = Voter()
        voter.user = request.user
        voter.question = question
        if voter.voted_already():
            voter_to_change = Voter.objects.get(user=request.user, question=question)
            answer_to_change = question.question_votes_counters.get(id=voter_to_change.answer.id)
            answer_to_change.votes -= 1
            answer_to_change.save()
            voter_to_change.answer = selected_answer
            voter_to_change.save()
        else:
            voter.answer = selected_answer
            voter.save()

        max_votes_answer = question.question_votes_counters.order_by('-votes').first()
        question.result = max_votes_answer.answer.answer
        question.save()

        return HttpResponseRedirect(reverse('polls:result', args=(question.id,)))
    else:
        max_votes_answer = question.question_votes_counters.order_by('-votes').first()
        return render(request, 'polls/question.html', {
            'question': question,
            'error_message': "Please, choose an answer",
            'max_votes_answer': max_votes_answer,
        })


@login_required
def result(request, question_id):
    question = get_object_or_404(Question, id=question_id)
    max_votes_answer = question.question_votes_counters.order_by('-votes').first()

    return render(request, 'polls/result.html', {
        'question': question,
        'max_votes_answer': max_votes_answer,
    })


@login_required
def new_poll(request):
    if request.method == 'GET':
        form = QuestionForm()
        return render(request, 'polls/newpoll.html', context={'form': form})
    else:
        form = QuestionForm(request.POST, files=request.FILES)
        if form.is_valid():
            form.save()

            question_qs = Question.objects.filter(date_published=date.today())

            for each in question_qs:
                question_pk = each.pk
                question = Question.objects.get(pk=question_pk)
                answers = each.answers.all()

            for each in answers:
                VotesCounter.objects.create(answer=each, question=question)

            return HttpResponseRedirect(reverse('polls:questions'))
        else:
            return render(request, 'polls/newpoll.html', context={'form': form})


@login_required
def update(request):
    answers = Answer.objects.all()
    for each in answers:
        each.is_active = False
        each.save()

    answers = list(answers)
    random_number_1 = randrange(2, len(answers))
    random_answers = random.sample(answers, random_number_1)

    Description.objects.filter(date_published=date.today()).delete()
    for each in random_answers:
        answer_to_change = Answer.objects.get(answer=each)
        answer_to_change.is_active = True
        answer_to_change.save()
        info = list(Info.objects.all())
        random_number_2 = randrange(2, 4)
        random_info = random.sample(info, random_number_2)

        for item in random_info:
            Description.objects.create(answer=each, text_info=item, digital_info=randrange(1, 100))

    today_description = Description.objects.filter(date_published=date.today())

    return render(request, "polls/update.html", context={'today_description': today_description,
                                                         'today_answers': random_answers})

polls/templates/polls/add_answer.html
{% extends "base.html" %}

{% block title %}
    Add answer
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Save</button>
    </form>
{% endblock %}

polls/templates/polls/detail.html
{% extends "base.html" %}

{% block title %}
    Question
{% endblock %}

{% block content %}
    <h1>{{ question.title }}</h1>
    <br>
    {{ max_votes_answer }} - {{ max_votes_answer.votes }}
    <hr>

    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}

    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        {% for answer in question.answers.all %}
            <input type="radio"
                   name="answer"
                   value="{{ answer.id }}" />
                {{ answer }}
                <br>
                <ul>
                    {% for each_answer in answer.answer_id.description_set.all %}
                        <li>
                        {{ each_answer.description }} {{ each_answer.digital_info }}
                        </li>
                    {% endfor %}
                </ul>
        {% endfor %}
         <br>
        <input type="submit" value="Vote" />
    </form>
{% endblock %}

polls/templates/polls/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Home
{% endblock %}

{% block content %}
<img src="{% static 'images/undraw_investing_7u74.svg' %}"
     alt="Image"
     class="img-fluid img-absolute">

<div class="row mb-4" data-aos="fade-up" data-aos-delay="200">
    <div class="col-lg-6 mr-auto">
        <h1>Survey for your company</h1>
        <p class="mb-5">Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
        <div>
            {% if user.is_authenticated %}
                <a href="{% url 'polls:questions' %}" class="btn btn-primary mr-2 mb-2">
                    Vote
                </a>
            {% else %}
                <a href="{% url 'polls:login' %}" class="btn btn-primary mr-2 mb-2">
                    Sign in
                </a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

polls/templates/polls/login.html
{% extends "base.html" %}

{% block title %}
Login
{% endblock %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-primary" type="submit">Login</button> or <a href="{% url 'polls:register' %}">Create account</a>
</form>

{% endblock %}

polls/templates/polls/newpoll.html
{% extends "base.html" %}

{% block title %}
AddQuestion
{% endblock %}

{% block content %}


<div class="col-lg-8 col-md-10 mx-auto">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </form>
    </div>


{% endblock %}

polls/templates/polls/question.html
{% extends "base.html" %}

{% block title %}
    Question
{% endblock %}

{% block content %}
    <h3>{{ question.title }}</h3>

    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}

    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        {% for answer in question.question_votes_counters.all %}
            <input type="radio"
                   name="answer"
                   value="{{ answer.id }}" />
                {{ answer }}
                <br>
                <ul>
                    {% for each_answer in answer.answer.description_set.all %}
                        <li>
                        {{ each_answer.text_info }} {{ each_answer.digital_info }}
                        </li>
                    {% endfor %}
                </ul>
        {% endfor %}
         <br>
        <input type="submit" class="btn btn-primary" value="Vote" />
    </form>
{% endblock %}

polls/templates/polls/questions.html
{% extends "base.html" %}

{% block title %}
    Questions
{% endblock %}

{% block content %}
    {% if we_have_questions %}
    <h1 class="mt-4">Please vote</h1>
        <p>
            <ul>
                {% for question in we_have_questions %}
                    <li>
                        <a href="{% url 'polls:question' question_id=question.id %}">
                        {{ question.title }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </p>
    {% else %}
        <p>
            <h1>Sorry,</h1>
            <h1>there are no questions for today</h1>
        </p>
    {% endif %}
{% endblock %}

polls/templates/polls/register.html
{% extends "base.html" %}

{% block title %}
    Registration
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Registration</button>
    </form>
{% endblock %}

polls/templates/polls/result.html
{% extends "base.html" %}

{% block title %}
    Result
{% endblock %}

{% block content %}
    <h1>{{ question.title }}</h1>

    {{ max_votes_answer }} - votes: {{ max_votes_answer.votes }}
    <br>
    <hr>

    <ul>
    {% for answer in question.question_votes_counters.all|dictsortreversed:"votes" %}
        <li>{{ answer }} - votes: {{ answer.votes }}</li>
    {% endfor %}
    </ul>
{% endblock %}

polls/templates/polls/results.html
<a href="/">Home</a>
<h1>{{ question.title }}</h1>
<ul>
{% for answer in question.answers.all|dictsortreversed:"votes" %}
    <li>{{ answer }} - votes: {{ answer.votes }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:each_question' question.id %}">Vote again</a>

polls/templates/polls/update.html
{% extends "base.html" %}

{% block title %}
    Update
{% endblock %}

{% block content %}
    {% if today_answers %}
    <h1 class="mt-4">Today we have menu from</h1>
        <p>
            <ul>
                {% for answer in today_answers %}
                    <li>
                        {{ answer}}
                        <br>
                        <ul>
                            {% for each in today_description %}
                            {% if each.answer == answer %}
                                <li>
                                {{ each.text_info }} {{ each.digital_info }}
                                </li>
                            {% endif %}
                            {% endfor %}
                        </ul>
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </p>
    {% else %}
        <p>
            <h1>Sorry,</h1>
            <h1>there are no menu for today</h1>
        </p>
    {% endif %}
{% endblock %}