DjangoPolls/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from polls.api_views import QuestionViewSet, AnswerViewSet, VoteViewSet

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()

router.register(r'answers', AnswerViewSet)
router.register(r'questions', QuestionViewSet)
router.register(r'votes', VoteViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls', namespace="polls")),
    path('api-auth/', include('rest_framework.urls')),
    path('api/v0/', include(router.urls)),
]

polls/urls.py
from django.urls import path
from polls import views
from django.contrib.auth.views import LogoutView

app_name = 'polls'

urlpatterns = [
    path('', views.main_view, name='index'),
    path('questions/', views.QuestionsListView.as_view(), name='questions'),
    path('<int:question_id>/', views.question_detail_view, name='question'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('<int:question_id>/result/', views.result, name='result'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.UserCreateView.as_view(), name='register'),
    path('newpoll/', views.new_poll, name='newpoll'),
    path('update/', views.update, name='update'),

]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Nunito:300,400,700" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">
    <!-- CSS for this template-->
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
          crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.fancybox.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/aos.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">

<div id="overlayer"></div>
<div class="loader">
    <div class="spinner-border text-primary" role="status">
        <span class="sr-only">Loading...</span>
    </div>
</div>

<div class="site-wrap" id="home-section">

    <div class="site-mobile-menu site-navbar-target">
        <div class="site-mobile-menu-header">
            <div class="site-mobile-menu-close mt-3">
                <span class="icon-close2 js-menu-toggle"></span>
            </div>
        </div>
        <div class="site-mobile-menu-body"></div>
    </div>

    <header class="site-navbar py-4 js-sticky-header site-navbar-target" role="banner">
        <div class="container">
            <div class="row align-items-center">

                <div class="col-6 col-md-3 col-xl-4  d-block">
                    <h1 class="mb-0 site-logo">
                        <a href="/" class="text-black h2 mb-0">
                            engagement
<!--                            <span class="text-primary">.</span>-->
                        </a>
                    </h1>
                </div>


                <div class="col-12 col-md-9 col-xl-8 main-menu">
                    <nav class="site-navigation position-relative text-right" role="navigation">
                        <ul class="site-menu main-menu js-clone-nav mr-auto d-none d-lg-block ml-0 pl-0">
                            {% if user.is_authenticated %}
                            <li><a href="{% url 'polls:questions' %}">Vote</a></li>
                            <li><a href="{% url 'polls:newpoll' %}">Create survey</a></li>
                            <li><a href="{% url 'polls:update' %}">Update</a></li>
                            <li><a href="{% url 'polls:logout' %}">({{user.username}}) Log out</a></li>
                            {% else %}

                            {% endif %}
                        </ul>
                    </nav>
                </div>

                <div class="col-6 col-md-9 d-inline-block d-lg-none ml-md-0">
                    <a href="#" class="site-menu-toggle js-menu-toggle text-black float-right">
                        <span class="icon-menu h3"></span>
                    </a>
                </div>


            </div>
        </div>
    </header>

    <div class="site-blocks-cover" style="overflow: hidden;">
        <div class="container">
            <div class="row align-items-center justify-content-center">
                <div class="col-md-12" style="position: relative;" data-aos="fade-up" data-aos-delay="200">

                    {% block content %}
                    {% endblock %}

                </div>
            </div>
        </div>
    </div>

    <!--    footer-->
    <div class="footer py-4 text-center">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <p class="mb-0">
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;<script>document.write(new Date().getFullYear());</script>
                        All rights reserved
                        <br>
                        This template is made with
                        <i class="icon-heart text-danger" aria-hidden="true"></i> by
                        <a href="https://colorlib.com" target="_blank">Colorlib</a>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </p>
                </div>
            </div>
        </div>
    </div>

</div> <!-- .site-wrap -->

<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/jquery-ui.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.countdown.min.js' %}"></script>
<script src="{% static 'js/bootstrap-datepicker.min.js' %}"></script>
<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
<script src="{% static 'js/aos.js' %}"></script>
<script src="{% static 'js/jquery.fancybox.min.js' %}"></script>
<script src="{% static 'js/jquery.sticky.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

</body>
</html>